//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abakon15WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pl-PL")]
        public string _Language {
            get {
                return ((string)(this["_Language"]));
            }
            set {
                this["_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _partnerId_DGHeader {
            get {
                return ((bool)(this["_partnerId_DGHeader"]));
            }
            set {
                this["_partnerId_DGHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _partnerCode_DGHeader {
            get {
                return ((bool)(this["_partnerCode_DGHeader"]));
            }
            set {
                this["_partnerCode_DGHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_NrEwid_ColumnVisibility {
            get {
                return ((bool)(this["_1_NrEwid_ColumnVisibility"]));
            }
            set {
                this["_1_NrEwid_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_NrInwentarzowy_ColumnVisibility {
            get {
                return ((bool)(this["_1_NrInwentarzowy_ColumnVisibility"]));
            }
            set {
                this["_1_NrInwentarzowy_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_ProducentId_ColumnVisibility {
            get {
                return ((bool)(this["_1_ProducentId_ColumnVisibility"]));
            }
            set {
                this["_1_ProducentId_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_NrFabryczny_ColumnVisibility {
            get {
                return ((bool)(this["_1_NrFabryczny_ColumnVisibility"]));
            }
            set {
                this["_1_NrFabryczny_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_SymbolProducenta_ColumnVisibility {
            get {
                return ((bool)(this["_1_SymbolProducenta_ColumnVisibility"]));
            }
            set {
                this["_1_SymbolProducenta_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_RokProdukcji_ColumnVisibility {
            get {
                return ((bool)(this["_1_RokProdukcji_ColumnVisibility"]));
            }
            set {
                this["_1_RokProdukcji_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_TypWlasnosci_ColumnVisibility {
            get {
                return ((bool)(this["_1_TypWlasnosci_ColumnVisibility"]));
            }
            set {
                this["_1_TypWlasnosci_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_Legalizacja_ColumnVisibility {
            get {
                return ((bool)(this["_1_Legalizacja_ColumnVisibility"]));
            }
            set {
                this["_1_Legalizacja_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_CzasokresSprawdzania_ColumnVisibility {
            get {
                return ((bool)(this["_1_CzasokresSprawdzania_ColumnVisibility"]));
            }
            set {
                this["_1_CzasokresSprawdzania_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_DataOstatniegoBadania_ColumnVisibility {
            get {
                return ((bool)(this["_1_DataOstatniegoBadania_ColumnVisibility"]));
            }
            set {
                this["_1_DataOstatniegoBadania_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_StopienZuzycia_ColumnVisibility {
            get {
                return ((bool)(this["_1_StopienZuzycia_ColumnVisibility"]));
            }
            set {
                this["_1_StopienZuzycia_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_WynikBadania_ColumnVisibility {
            get {
                return ((bool)(this["_1_WynikBadania_ColumnVisibility"]));
            }
            set {
                this["_1_WynikBadania_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_DataNastepnegoBadania_ColumnVisibility {
            get {
                return ((bool)(this["_1_DataNastepnegoBadania_ColumnVisibility"]));
            }
            set {
                this["_1_DataNastepnegoBadania_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_Uwagi_ColumnVisibility {
            get {
                return ((bool)(this["_1_Uwagi_ColumnVisibility"]));
            }
            set {
                this["_1_Uwagi_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_WlascicielId_ColumnVisibility {
            get {
                return ((bool)(this["_1_WlascicielId_ColumnVisibility"]));
            }
            set {
                this["_1_WlascicielId_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_MiejsceUzytkowaniaId_ColumnVisibility {
            get {
                return ((bool)(this["_1_MiejsceUzytkowaniaId_ColumnVisibility"]));
            }
            set {
                this["_1_MiejsceUzytkowaniaId_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_UzytkownikId_ColumnVisibility {
            get {
                return ((bool)(this["_1_UzytkownikId_ColumnVisibility"]));
            }
            set {
                this["_1_UzytkownikId_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_ApplicationId_ColumnVisibility {
            get {
                return ((bool)(this["_1_ApplicationId_ColumnVisibility"]));
            }
            set {
                this["_1_ApplicationId_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_CreateDate_ColumnVisibility {
            get {
                return ((bool)(this["_1_CreateDate_ColumnVisibility"]));
            }
            set {
                this["_1_CreateDate_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_LastUpdateDate_ColumnVisibility {
            get {
                return ((bool)(this["_1_LastUpdateDate_ColumnVisibility"]));
            }
            set {
                this["_1_LastUpdateDate_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_UserName_ColumnVisibility {
            get {
                return ((bool)(this["_1_UserName_ColumnVisibility"]));
            }
            set {
                this["_1_UserName_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_budowa_ColumnVisibility {
            get {
                return ((bool)(this["_1_budowa_ColumnVisibility"]));
            }
            set {
                this["_1_budowa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_dzialka_ColumnVisibility {
            get {
                return ((bool)(this["_1_dzialka_ColumnVisibility"]));
            }
            set {
                this["_1_dzialka_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_obszar_ColumnVisibility {
            get {
                return ((bool)(this["_1_obszar_ColumnVisibility"]));
            }
            set {
                this["_1_obszar_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_zakresy_ColumnVisibility {
            get {
                return ((bool)(this["_1_zakresy_ColumnVisibility"]));
            }
            set {
                this["_1_zakresy_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_klasa_ColumnVisibility {
            get {
                return ((bool)(this["_1_klasa_ColumnVisibility"]));
            }
            set {
                this["_1_klasa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_napiecie_ColumnVisibility {
            get {
                return ((bool)(this["_1_napiecie_ColumnVisibility"]));
            }
            set {
                this["_1_napiecie_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_pradRob_ColumnVisibility {
            get {
                return ((bool)(this["_1_pradRob_ColumnVisibility"]));
            }
            set {
                this["_1_pradRob_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_pradStaly_ColumnVisibility {
            get {
                return ((bool)(this["_1_pradStaly_ColumnVisibility"]));
            }
            set {
                this["_1_pradStaly_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_pradZmienny_ColumnVisibility {
            get {
                return ((bool)(this["_1_pradZmienny_ColumnVisibility"]));
            }
            set {
                this["_1_pradZmienny_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_dzialka1_ColumnVisibility {
            get {
                return ((bool)(this["_1_dzialka1_ColumnVisibility"]));
            }
            set {
                this["_1_dzialka1_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_obszar1_ColumnVisibility {
            get {
                return ((bool)(this["_1_obszar1_ColumnVisibility"]));
            }
            set {
                this["_1_obszar1_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_wgran_ColumnVisibility {
            get {
                return ((bool)(this["_1_wgran_ColumnVisibility"]));
            }
            set {
                this["_1_wgran_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_wysieg_ColumnVisibility {
            get {
                return ((bool)(this["_1_wysieg_ColumnVisibility"]));
            }
            set {
                this["_1_wysieg_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_nacisk_ColumnVisibility {
            get {
                return ((bool)(this["_1_nacisk_ColumnVisibility"]));
            }
            set {
                this["_1_nacisk_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_klasa1_ColumnVisibility {
            get {
                return ((bool)(this["_1_klasa1_ColumnVisibility"]));
            }
            set {
                this["_1_klasa1_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_wzorzec_ColumnVisibility {
            get {
                return ((bool)(this["_1_wzorzec_ColumnVisibility"]));
            }
            set {
                this["_1_wzorzec_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_Zrodlo_ColumnVisibility {
            get {
                return ((bool)(this["_1_Zrodlo_ColumnVisibility"]));
            }
            set {
                this["_1_Zrodlo_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par1Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par1Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par1Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par1Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par1Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par1Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par1Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par1Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par1Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par2Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par2Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par2Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par2Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par2Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par2Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par2Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par2Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par2Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par3Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par3Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par3Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par3Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par3Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par3Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par4Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par4Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par4Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par4Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par4Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par4Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par4Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par4Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par4Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par5Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par5Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par5Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par5Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par5Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par5Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par5Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par5Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par5Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par6Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par6Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par6Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par6Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par6Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par6Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par6Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par6Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par6Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par7Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par7Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par7Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par7Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par7Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par7Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par7Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par7Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par7Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par8Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par8Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par8Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par8Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par8Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par8Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par8Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par8Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par8Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par9Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par9Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par9Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par9Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par9Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par9Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par9Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par9Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par9Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par10Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par10Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par10Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par10Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par10Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par10Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par10Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par10Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par10Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par11Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par11Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par11Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par11Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par11Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par11Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par11Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par11Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par11Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par12Nazwa_ColumnVisibility {
            get {
                return ((bool)(this["_1_par12Nazwa_ColumnVisibility"]));
            }
            set {
                this["_1_par12Nazwa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par12Wartosc_ColumnVisibility {
            get {
                return ((bool)(this["_1_par12Wartosc_ColumnVisibility"]));
            }
            set {
                this["_1_par12Wartosc_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_par12Wynik_ColumnVisibility {
            get {
                return ((bool)(this["_1_par12Wynik_ColumnVisibility"]));
            }
            set {
                this["_1_par12Wynik_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_TypSprGwintow_ColumnVisibility {
            get {
                return ((bool)(this["_1_TypSprGwintow_ColumnVisibility"]));
            }
            set {
                this["_1_TypSprGwintow_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_TypGwintu_ColumnVisibility {
            get {
                return ((bool)(this["_1_TypGwintu_ColumnVisibility"]));
            }
            set {
                this["_1_TypGwintu_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_NumerNormyNaGwint_ColumnVisibility {
            get {
                return ((bool)(this["_1_NumerNormyNaGwint_ColumnVisibility"]));
            }
            set {
                this["_1_NumerNormyNaGwint_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_Wewn_Zewn_ColumnVisibility {
            get {
                return ((bool)(this["_1_Wewn_Zewn_ColumnVisibility"]));
            }
            set {
                this["_1_Wewn_Zewn_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_Srednica_ColumnVisibility {
            get {
                return ((bool)(this["_1_Srednica_ColumnVisibility"]));
            }
            set {
                this["_1_Srednica_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_Skok_ColumnVisibility {
            get {
                return ((bool)(this["_1_Skok_ColumnVisibility"]));
            }
            set {
                this["_1_Skok_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_Discriminator_ColumnVisibility {
            get {
                return ((bool)(this["_1_Discriminator_ColumnVisibility"]));
            }
            set {
                this["_1_Discriminator_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_PrzyrzadPomiarowyNrKod_ColumnVisibility {
            get {
                return ((bool)(this["_1_PrzyrzadPomiarowyNrKod_ColumnVisibility"]));
            }
            set {
                this["_1_PrzyrzadPomiarowyNrKod_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_SelectedEquipmentType_ColumnVisibility {
            get {
                return ((bool)(this["_1_SelectedEquipmentType_ColumnVisibility"]));
            }
            set {
                this["_1_SelectedEquipmentType_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_DataGwarancji_ColumnVisibility {
            get {
                return ((bool)(this["_1_DataGwarancji_ColumnVisibility"]));
            }
            set {
                this["_1_DataGwarancji_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid PathToPatterns {
            get {
                return ((global::System.Guid)(this["PathToPatterns"]));
            }
            set {
                this["PathToPatterns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid PathToDocuments_CollectionOfEquipment {
            get {
                return ((global::System.Guid)(this["PathToDocuments_CollectionOfEquipment"]));
            }
            set {
                this["PathToDocuments_CollectionOfEquipment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undefined")]
        public string _DB_server {
            get {
                return ((string)(this["_DB_server"]));
            }
            set {
                this["_DB_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undefined")]
        public string _DB_user {
            get {
                return ((string)(this["_DB_user"]));
            }
            set {
                this["_DB_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid PathToDocuments_SingleEquipment {
            get {
                return ((global::System.Guid)(this["PathToDocuments_SingleEquipment"]));
            }
            set {
                this["PathToDocuments_SingleEquipment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedPattern_SingleEquipment {
            get {
                return ((string)(this["LastSelectedPattern_SingleEquipment"]));
            }
            set {
                this["LastSelectedPattern_SingleEquipment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedPattern_CollectionOfEquipment {
            get {
                return ((string)(this["LastSelectedPattern_CollectionOfEquipment"]));
            }
            set {
                this["LastSelectedPattern_CollectionOfEquipment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _DB_psw {
            get {
                return ((string)(this["_DB_psw"]));
            }
            set {
                this["_DB_psw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _9_PartnerCode_ColumnVisibility {
            get {
                return ((bool)(this["_9_PartnerCode_ColumnVisibility"]));
            }
            set {
                this["_9_PartnerCode_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _9_PartnerName_ColumnVisibility {
            get {
                return ((bool)(this["_9_PartnerName_ColumnVisibility"]));
            }
            set {
                this["_9_PartnerName_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _9_PartnerType_ColumnVisibility {
            get {
                return ((bool)(this["_9_PartnerType_ColumnVisibility"]));
            }
            set {
                this["_9_PartnerType_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _9_Partnerphone_ColumnVisibility {
            get {
                return ((bool)(this["_9_Partnerphone_ColumnVisibility"]));
            }
            set {
                this["_9_Partnerphone_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _9_PartnerFax_ColumnVisibility {
            get {
                return ((bool)(this["_9_PartnerFax_ColumnVisibility"]));
            }
            set {
                this["_9_PartnerFax_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _9_PartnerEmail_ColumnVisibility {
            get {
                return ((bool)(this["_9_PartnerEmail_ColumnVisibility"]));
            }
            set {
                this["_9_PartnerEmail_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _9_PartnerWWW_ColumnVisibility {
            get {
                return ((bool)(this["_9_PartnerWWW_ColumnVisibility"]));
            }
            set {
                this["_9_PartnerWWW_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _9_PartnerKeyWords_ColumnVisibility {
            get {
                return ((bool)(this["_9_PartnerKeyWords_ColumnVisibility"]));
            }
            set {
                this["_9_PartnerKeyWords_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _9_PartnerReliabilityRating_ColumnVisibility {
            get {
                return ((bool)(this["_9_PartnerReliabilityRating_ColumnVisibility"]));
            }
            set {
                this["_9_PartnerReliabilityRating_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_NrSAP_ColumnVisibility {
            get {
                return ((bool)(this["_1_NrSAP_ColumnVisibility"]));
            }
            set {
                this["_1_NrSAP_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _1_SubGrupa_ColumnVisibility {
            get {
                return ((bool)(this["_1_SubGrupa_ColumnVisibility"]));
            }
            set {
                this["_1_SubGrupa_ColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double EquipmentSpliter {
            get {
                return ((double)(this["EquipmentSpliter"]));
            }
            set {
                this["EquipmentSpliter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double EquipmentSpliterV {
            get {
                return ((double)(this["EquipmentSpliterV"]));
            }
            set {
                this["EquipmentSpliterV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undefined")]
        public string _DB_Name {
            get {
                return ((string)(this["_DB_Name"]));
            }
            set {
                this["_DB_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _DB_Authetification {
            get {
                return ((bool)(this["_DB_Authetification"]));
            }
            set {
                this["_DB_Authetification"] = value;
            }
        }
    }
}
